org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon.idletimeout=900000
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.caching=true
org.gradle.configuration-cache=false
kotlin.daemon.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
android.experimental.testOptions.managedDevices.allowOldApiLevelDevices=true
kotlin.code.style=official
